[package]
name = "advent-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
byte_set = "0.1.3"
itertools = "0.12.0"
thiserror = "1.0.50"
winnow = "0.5.19"
